# Generated by Django 4.2.25 on 2026-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
