# Generated by Django 4.2.25 on 2026-07-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupstation',
            name='phone',
        ),
    ]
