# Generated by Django 4.2.25 on 2026-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags e.g. phone,smartphone,android', max_length=500),
        ),
    ]
